export const FETCH_UPCOMING_CARS_REQUEST = "FETCH_UPCOMING_CARS_REQUEST";
export const FETCH_UPCOMING_CARS_SUCCESS = "FETCH_UPCOMING_CARS_SUCCESS";
export const FETCH_UPCOMING_CARS_FAILURE = "FETCH_UPCOMING_CARS_FAILURE";

export const FETCH_TRENDING_CARS_REQUEST = "FETCH_TRENDING_CARS_REQUEST";
export const FETCH_TRENDING_CARS_SUCCESS = "FETCH_TRENDING_CARS_SUCCESS";
export const FETCH_TRENDING_CARS_FAILURE = "FETCH_TRENDING_CARS_FAILURE";
